### PR TITLE
empty image hash fix

### PR DESCRIPTION
**Pull request by Pfabeck**
| Q                         | A
| ------------------------- | ---
| issue or Enhancement      | issue|

#### What's in this PR?
import images without hash

### CODE REVIEW

**Comment by smxvh** [comment]
HI, 
I don't understand the changee in Adapter/PlentymarketsAdapter/ResponseParser/Product/Image/ImageResponseParser.php on  line 111 
` 'name' => $entry['names'][0]['name'],`

on lines 63-67 is the logic, that handles $name:
`
        if (!empty($entry['names'][0]['name'])) {
                $name = $entry['names'][0]['name'];
            } else {
                $name = $texts[0]['name1'];
            }
`
This is but in catch block not respected:


The solution shoould be:

- separate getting name to method and on both places this method call
- The solution, that is im https://github.com/plentymarkets/plentymarkets-shopware-connector/commit/35cb55820aa05ec94bfb39716140ef36f62de9ee

**Comment by Pfabeck** [comment]
There is no index name in $entry. (PHP Notice:  Undefined index: name)

**Comment by jochenmanz** [comment]
We should use the id here, as implemented and merged an hour ago :)

**Comment by Pfabeck** [comment]
;)

**Pull request merged**
