### PR TITLE
various fixes and improvements

### PR DESCRIPTION
**Pull request by jppeter**
new features:
- configure whether product-descriptions, keywords, freetexts should be imported or not
- adds the possibility of email-alert in case of failure (mapping / data integrity)

fixes:
- delays the export of orders with amazon payment to prevent missing address-data ("empty" customer)
- surcharges and discounts will now be imported with articleID -1 instead of -2  
- updated the required shopware-version to 4.3, because it didn't work correctly in the older versions

p.s. sorry for replacement of tabs with spaces... but it's much better now :)

### CODE REVIEW

**Comment by jppeter** [comment]
missing feature:
- the product name (name, name2 or name3) is now selectable

**Comment by joconja** [comment]
Kannst du die Sachen ggf. in einzelne Pull Requests machen?

**Comment by jppeter** [comment]
Tzzzz :D Na gut, mache das mal fertig ;)

**Comment by bvogel** [comment]
@jppeter Das waren ein paar coole Sachen die du da eingebaut hast und ich gerne im "offiziellen" Connector sehen würde. Könntest du da doch noch PRs dafür generieren? Danke!

**Pull request closed without merging**
