### PR TITLE
Storage expansion

### PR DESCRIPTION
**Pull request by jochenmanz**
| Q                         | A
| ------------------------- | ---
| issue or Enhancement      | issue|Enhancement
| Changelog updated?        | no|yes
| License                   | MIT

#### What's in this PR?

Explain what the changes in this PR do.

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix

### CODE REVIEW

**Comment by florianliebig** [comment]
I'm getting the following error when checking out the StorageExpansion branch (and using composer update / composer install):

`In DBALException.php line 131:

  An exception occurred while executing 'SELECT count(id) FROM ?' with params ["plenty_backlog"]:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''plenty_backlog'' at line 1


In Connection.php line 847:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''plenty_backlog'' at line 1
`

**Comment by jochenmanz** [comment]
@florianliebig thanks for testing! i have pushed a fix for this problem :)

**Comment by florianliebig** [comment]
Is there any smart way to add name2 and name3 to existing products? I did a new transfer but these new attributes are not in the item set. Or is it necessary to delete products and do a full new sync?  Maybe also a point for documentation.

**Comment by jochenmanz** [comment]
@florianliebig after installing the new code a full sync (plentyconnector:process product --all) should be all you need to do. I was not able to reproduce your problem on my installation :(

**Comment by jochenmanz** [comment]
@florianliebig i think i found a potential error. Could you recheck on your system?

**Comment by florianliebig** [comment]
@jochenmanz It works now on the existing installation thank you very much!

**Pull request merged**
